function Hd = MSK_filter
%MSK_FILTER Returns a discrete-time filter object.
 
% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 01-Jun-2020 18:06:12
 
% Equiripple Lowpass filter designed using the FIRPM function.
 
% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency
Fpass = 2;               % Passband Frequency
Fstop = 8;              % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor
 
% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
 
% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);
 
% [EOF]
